version: '3'
services:
    nginx:
        build: ./docker/nginx
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/log/nginx:/var/log/nginx/"
            - "./:/var/www/example"
        ports:
            - "80:80"
            - "3000:443"
        restart: always
        links:     
            - php-fpm
    php-fpm:
        build: ./docker/php-fpm
        restart: always
        volumes:
            - "./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/example"
        links:     
            - mysql
    mysql:
        build: ./docker/mysql
        environment:
            MYSQL_DATABASE: example
            MYSQL_ROOT_PASSWORD: Root-123
            MYSQL_USER: user
            MYSQL_PASSWORD: user123
        ports:
            - "3306:3306"
        volumes:
            - "./docker/mysql/lib:/var/lib/mysql"
            - "./docker/mysql/dump/dump.sql:/docker-entrypoint-initdb.d/init.sql"
